// ** React Imports
import { Fragment, useEffect, useState } from 'react'

// ** MUI Imports
import { Dialog, DialogTitle, DialogContent, DialogContentText, Divider, IconButton, Typography, Box, Card } from '@mui/material';
import CloseIcon from '@mui/icons-material/Close';

const DialogTermsAndConditions = ({ open, title, content, onConfirm, onCancel, loading = false }) => {
    // ** State
    const [openDialog, setOpenDialog] = useState(false)

    // Effect to open or close the dialog when the `open` prop changes
    useEffect(() => {
        setOpenDialog(open)
    }, [open])


    return (
        <Fragment>
            <Dialog
                open={openDialog}
                onClose={(event, reason) => {
                    if (reason !== 'backdropClick') {
                        onCancel()
                    }
                }}
                aria-labelledby="custom-dialog-title"
                aria-describedby="custom-dialog-description"
                maxWidth="md" // Set the dialog size to 'lg'
                fullWidth // Ensures the dialog takes full width of the maxWidth
            >
                {/* Dialog Title with Close Icon */}
                <DialogTitle
                    id="custom-dialog-title"
                    sx={{
                        display: 'flex',
                        justifyContent: 'space-between',
                        alignItems: 'center',
                    }}
                >
                    <Typography variant="h6" component="span" fontWeight="bold">
                        {title}
                    </Typography>
                    <IconButton
                        aria-label="close"
                        onClick={() => {
                            // Add your close logic here
                            onCancel();
                        }}
                        sx={{ color: (theme) => theme.palette.grey[500] }}
                    >
                        <CloseIcon />
                    </IconButton>
                </DialogTitle>

                {/* Divider under the title */}
                <Divider />

                {/* Dialog Content */}
                <DialogContent>
                    <Box sx={{ width: '100%', flexDirection: 'column' }}>
                        <Typography variant="h6" sx={{ fontWeight: 'bold' }}>
                            TERMS OF USE
                        </Typography>
                        <Typography variant="body1" sx={{ color: 'text.secondary', mt: 4 }}>
                            This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                        </Typography>
                        <Typography variant="body1" sx={{ color: 'text.secondary', mt: 4 }}>
                            This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of www.pincinsurance.com, mobile applications that is Kaito INSURANCE, Kaito Strides Health Insurance, Kaito CRM, Kaito TREE (POS based application) and various mobile applications.
                        </Typography>
                        <Typography variant="body1" sx={{ color: 'text.secondary', mt: 4 }}>
                            THESE TERMS OF USE (THE "TERMS OF USE") ARE ISSUED BY PIONEER INSURANCE AND REINSURANCE BROKERS PVT. LTD. AND ITS DIRECTLY AND INDIRECTLY RELATED COMPANIES (HEREINAFTER, “PINC INSURANCE”). THEY APPLY TO ALL WEBSITES, BLOGGING SITES, APPLICATIONS AND OTHER ONLINE DIALOGUE PLATFORMS OWNED OR MANAGED BY OR ON BEHALF OF Kaito INSURANCE UNDER THE URL PINCINSURE.COM
                        </Typography>
                        <Typography variant="body1" sx={{ color: 'text.secondary', mt: 4 }}>
                            By accessing the Kaito INSURANCE site/applications and any page thereof, you agree to be bound by these terms of use and to comply with any applicable laws and regulations. If you do not agree to these Terms of Use, do not proceed to further pages of the Kaito INSURANCE.
                        </Typography>
                        <Typography variant="body1" sx={{ color: 'text.secondary', mt: 4 }}>
                            Kaito INSURANCE reserves the right to vary or amend these Terms of Use at any time and Kaito INSURANCE is under no obligation to inform you about such variations or amendments. The most recent version of the Terms of Use will govern the services on Kaito INSURANCE website/ application and will always be available on the Kaito INSURANCE website and application. By continuing to access or use this Kaito INSURANCE Website/Applications after any changes become effective, you agree to be bound by the revised Terms of Use. Please visit these Terms of Use on a regular basis to ensure that you have read the latest version. These Terms of Use were updated the last time on the date indicated at the end of the Terms of Use.
                        </Typography>
                        <Typography variant="body1" sx={{ color: 'text.secondary', mt: 4 }}>
                            The headings used for each of the paragraphs of these Terms of Use do not affect its interpretation. The reference to a “person” is a reference to an individual, a body corporate and an unincorporated association of persons.
                        </Typography>
                        <Typography variant="body1" sx={{ color: 'text.secondary', mt: 4 }}>
                            Our participating insurance providers supply some of the information available on the Website/Applications and therefore there may be differences in the website/applications information, over which Kaito INSURANCE has limited control. For details about any insurance policy, do contact our advisors or refer the brochure provided on the Website/ Applications of the insurance provider.
                        </Typography>
                        <Typography variant="body1" sx={{ color: 'text.secondary', mt: 4 }}>
                            To the maximum extent permitted by law, Kaito INSURANCE has no liability in relation to or arising out of the website/ applications information and recommendations. You are responsible for the final choice of your services and you should take time to read through all information supplied before proceeding. If you are in any doubt regarding a services or its terms, you should seek further advice from Kaito INSURANCE or the relevant participating provider before choosing your services.
                        </Typography>
                        <Typography variant="body1" sx={{ color: 'text.secondary', mt: 4 }}>
                            Note that Kaito INSURANCE only assists collecting the premium instrument on behalf of the Insurance Companies you have chosen to buy the policy from; Kaito INSURANCE itself does not collect any premium. The acceptance of the amount as premium and final issuance of the policy is subject to the underwriting norms and discretion of the respective Insurance Companies whose policy you have chosen to buy, over which Kaito INSURANCE has no control. Kaito INSURANCE will ensure that the Insurance Companies refunds the amount in case there is no ultimate issuance of the policy.
                        </Typography>
                        <Typography variant="body1" sx={{ color: 'text.secondary', mt: 4 }}>
                            Kaito INSURANCE may pass on your personal information to the relevant participating provider if you apply to purchase a services through www.pincinsurance.com and/or its mobile applications that is Kaito INSURANCE, Kaito Strides Health Insurance, Kaito CRM, Kaito TREE (POS based application) and various other mobile applications; however, Kaito INSURANCE does not guarantee when or if you will actually acquire the services that you have chosen. Kaito INSURANCE does not accept any liability arising out of circumstances where there is delay in receiving the services you have chosen.
                        </Typography>
                        <Typography variant="body1" sx={{ color: 'text.secondary', mt: 4 }}>
                            For the purpose of these Terms of Use, “Content” means any text, written work, software, database, format, graphic, image, photo, video clip, podcast, listing or any other information or material which appears on or forms part of a Kaito INSURANCE Website and Applications.
                        </Typography>

                        <Typography variant="h6" sx={{ mt: 4, fontWeight: 'bold' }}>
                            Company Information and Website / applications Operation
                        </Typography>

                        <Typography variant="body1" sx={{ color: 'text.secondary', mt: 4 }}>
                            Kaito INSURANCE is a composite insurance brokerage house, registered with Insurance Regulatory Development Authority of India (IRDA) as composite Insurance Broker having License no.118 (valid up to 23/02/2024) providing direct general and life insurance broking services in India and reinsurance services across the world. As a risk advisor, insurance and reinsurance broker in India, we leverage our superior expertise, teamwork and innovation to provide professional services in risk management and risk transfer across geographies. Licensed by the Insurance Regulatory and Development Authority of India (IRDA) since 2003, Kaito INSURANCE handles underwriting, claims, reinsurance and risk management for a diverse client base across industry sectors. Kaito INSURANCE site and/or its mobile applications that is Kaito INSURANCE, Kaito Strides Health Insurance Kaito CRM, Kaito TREE (POS based application) and various other mobile applications includes content relating to Kaito INSURANCE and its businesses provided by Pioneer Insurance and Reinsurance Brokers Pvt. Ltd. having registered office at 1219, 12th Floor, Maker Chambers V, Nariman Point, Mumbai – 400 021.                        </Typography>

                        <Typography variant="h6" sx={{ mt: 4, fontWeight: 'bold' }}>
                            Services and Solutions
                        </Typography>
                        <Typography variant="body1" sx={{ color: 'text.secondary', mt: 4 }}>
                            Kaito INSURANCE makes no guarantee, representation or warranty that all services, services and solutions described on Kaito INSURANCE Site/Applications are available for use in your country. Some services, services or solutions may not be available in all countries where Kaito INSURANCE has business activities. Therefore, please read carefully the relevant description on the respective Kaito INSURANCE Site/Applications or request further information about the relevant service or solution.
                        </Typography>
                        <Typography variant="body1" sx={{ color: 'text.secondary', mt: 4 }}>
                            Content available on Kaito INSURANCE Site/Applications has no regard to the specific objectives, financial situation or particular needs of any specific recipient. Kaito INSURANCE does not guarantee, represent or warrant that any services, services or solutions discussed on Kaito INSURANCE Site/Applications are suitable for any individual or corporate recipient. No representation or warranty, either express or implied, is provided in relation to the accuracy, completeness or reliability of Content, nor is content a complete statement of the services or solutions, markets or developments referred to therein. Content should not be regarded by recipients as a substitute for the exercise of their judgment. Any opinion is subject to change without notice and may differ or be contrary to opinions expressed by other business areas or members of Kaito INSURANCE as a result of using different assumptions and criteria.
                        </Typography>
                        <Typography variant="body1" sx={{ color: 'text.secondary', mt: 4 }}>
                            Content contained on Kaito INSURANCE Site/Applications is just for information purposes. The information is subject to, and must be read in conjunction with, all other publicly available information published by Insurance Companies offering their product or services.
                        </Typography>
                        <Typography variant="body1" sx={{ color: 'text.secondary', mt: 4 }}>
                            No Content available on Kaito INSURANCE Site/Applications constitutes a solicitation, an offer, or a recommendation to buy any services, services or solutions, to effect any transactions or to conclude any legal act of any kind whatsoever. You or your company may not rely on Content on a Kaito INSURANCE Site/Applications for making any decision relating to services
                        </Typography>

                        <Typography variant="body1" sx={{ color: 'text.secondary', mt: 4 }}>
                            In making Content available, Kaito INSURANCE gives no advice and makes no recommendation to buy, sell or otherwise deal in its shares, or in any other securities or investments whatsoever. The Content does not constitute or form part of, and should not be construed as, an offer for sale or subscription of, or solicitation of any offer or invitation to subscribe for, underwrite or otherwise acquire or dispose of any securities of Kaito INSURANCE. The Content does not constitute an invitation to effect any transaction with, or to make use of any services provided by, Kaito INSURANCE. Statements in Content as to historical performance or historical share price are not intended to mean that future performance or historical share price for any period will necessarily match or exceed those of any prior year. Nothing in Content should be construed as a profit forecast. The information and opinions are subject to change without notice.
                        </Typography>
                        <Typography variant="body1" sx={{ color: 'text.secondary', mt: 4 }}>
                            Responsible Use and Conduct
                        </Typography>
                        <Typography variant="body1" sx={{ color: 'text.secondary', mt: 4 }}>
                            By visiting our website/applications and accessing the information, resources, services, and tools we provide for you, either directly or indirectly (hereafter referred to as ‘Resources’), you agree to use these Resources only for the purposes intended as permitted by the terms of this Agreement and/or applicable laws, regulations and generally accepted online practices or guidelines.                        </Typography>
                        <Typography variant="body1" sx={{ color: 'text.secondary', mt: 4 }}>
                            Wherein, you understand that:
                        </Typography>
                        <Typography variant="body1" sx={{ color: 'text.secondary', mt: 4 }}>
                            • In order to access our Resources, you may be required to provide certain information
                            about yourself (such as name, address, contact details, car registration and purchase
                            details, identity proof such as Aadhaar ID, your location as well as your mobile camera
                            including storage facilities, policy details, card details, claim intimation and status
                            etc.).
                            You agree that any information you provide will always be accurate, correct, and
                            updated.
                        </Typography>
                        <Typography variant="body1" sx={{ color: 'text.secondary' }}>
                            • By providing your information you explicitly authorize us to access on your behalf your records from the competent authority, such as Aadhaar, RTO, etc. for the purpose of facilitation of your transaction with us.
                        </Typography>
                        <Typography variant="body1" sx={{ color: 'text.secondary'}}>
                            • You are responsible for maintaining the confidentiality of any login information associated with any account you use to access our Resources. Accordingly, you are responsible for all activities that occur under your account/s.
                        </Typography>


                        <Typography variant="h6" sx={{ mt: 4, fontWeight: 'bold' }}>
                        </Typography>
                        <Typography variant="body1" sx={{ color: 'text.secondary', mt: 4 }}>
                        </Typography>

                        <Typography variant="h6" sx={{ mt: 4, fontWeight: 'bold' }}>
                        </Typography>
                        <Typography variant="body1" sx={{ color: 'text.secondary', mt: 4 }}>
                        </Typography>

                        <Typography variant="h6" sx={{ mt: 4, fontWeight: 'bold' }}>
                        </Typography>
                        <Typography variant="body1" sx={{ color: 'text.secondary', mt: 4 }}>
                        </Typography>
                    </Box>
                </DialogContent>
            </Dialog>
        </Fragment>
    )
}

export default DialogTermsAndConditions
