export const rtoOptions = [
        "GJ01-AHMEDABAD",
        "GJ02-MEHSANA",
        "GJ04-BHAVNAGAR",
        "GJ05-SURAT",
        "GJ06-VADODARA",
        "MH17-SHRIRAMPUR",
        "MH18-DHULE",
        "MH19-JALGAON",
        "MH01-MUMBAI",
        "RJ29-DAUSA",
        "RJ30-RAJSAMAND",
        "RJ31-HANUMANGARH",
        "RJ32-KOTPUTLI",
        "RJ33-RAMGANJ MANDI",
        "RJ34-KARAULI",
        "UK16-VIKASNAGAR",
        "UK17-ROORKEE",
        "UK18-KASHIPUR",
        "UK19-RAMNAGAR",
        "UK20-RANIKHET",
        "UP76-FARRUKHABAD",
]

export const yearsOptions =[
    "2025", "2024", "2023", "2022", "2021", "2020", "2019", "2018", "2017", "2016",
    "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006",
    "2005", "2004", "2003", "2002", "2001"
]
export const cityOptions ={
    "ANDAMAN & NICOBAR ISLANDS": ["Port Blair"],
    "ANDHRA PRADESH": ["Anantapur", "Chittoor", "East Godavari", "Guntur", "Kadapa", "Krishna", "Kurnool", "Nellore", "Prakasam", "Srikakulam", "Visakhapatnam", "Vizianagaram", "West Godavari"],
    "ARUNACHAL PRADESH": ["Anjaw", "Changlang", "Dimapur", "Kiphire", "Kohima", "Longleng", "Mokokchung", "Mon", "Nongstoin", "Phek", "Phek", "Phek", "Tuensang", "Wokha", "Zunheboto"],
    "ASSAM": ["Dhubri", "Dibrugarh", "Goalpara", "Jorhat", "Nagaon", "Nalbari", "Sibsagar", "Sonitpur", "Tinsukia", "Udalguri"],
    "BIHAR": ["Arrah", "Bihar Sharif", "Bhagalpur", "Gaya", "Muzaffarpur", "Patna", "Purnia", "Sasaram"],
    "CHANDIGARH": ["Central Delhi", "East Delhi", "New Delhi", "North Delhi", "South Delhi", "West Delhi"],
    "CHATTISGARH": ["Bilaspur", "Durg", "Jagdalpur", "Raipur", "Rajnandgaon"],
    "GUJARAT": ["Ahmedabad", "Gandhinagar", "Rajkot", "Surat", "Vadodara"],
    "HARYANA": ["Ambala", "Faridabad", "Gurgaon", "Hisar", "Karnal", "Panchkula", "Rohtak"],
    "HIMACHAL PRADESH": ["Dharamshala", "Hamirpur", "Kullu", "Mandi", "Shimla", "Solan"]

}

export const carMakeList = [
    "CHEVROLET",
    "FORD",
    "SKODA",
    "BMW",
    "VOLKSWAGEN",
    "HYUNDAI",
    "NISSAN",
    "RENAULT",
    "FIAT",
    "TOYOTA",
    "MERCEDES-BENZ",
    "MAHINDRA",
    "MARUTI",
    "KIA",
    "HONDA",
    "TATA"
];

export const carModalList = {
    "chevrolet": ["Spark", "Beat", "Cruze", "Tavera", "Camaro", "Colorado", "Equinox", "Silverado", "Trailblazer", "Trax"],
    "ford": ["Figo", "Fiesta", "Ecosport", "Endeavour", "Mustang", "Fusion", "Focus", "Explorer", "Edge", "Escape"],
    "skoda": ["Rapid", "Octavia", "Superb", "Kodiaq", "Karoq", "Yeti", "Fabia", "Laura", "Superb"],
    "bmw": ["X1", "X2", "X3", "X4", "X5", "X6", "X7", "M2", "M3", "M4", "M5", "M6"],
    "volkswagen": ["Polo", "Vento", "Jetta", "Passat", "Tiguan", "Touareg", "Amarok", "Golf", "Jetta GLI", "Arteon"],
    "hyundai": ["Santro", "i20", "Verna", "Creta", "Tucson", "Elantra", "Santa Fe", "Kona", "Venue", "Grand i10"],
    "nissan": ["Micra", "Sunny", "Kicks", "Terrano", "GT-R", "Leaf", "Altima", "Pathfinder", "Rogue", "Xterra"],
    "renault": ["Kwid", "Duster", "Triber", "Koleos", "Captur", "Dacia Duster", "Lodgy", "Pulse", "Scala", "Fluence"],
    "fiat": ["Punto", "Linea", "500X", "Panda", "Linea Classic", "Avventura", "Urban Cross", "T-Jet", "Cronos"],
    "toyota": ["Altis", "Camry", "Corolla", "Highlander", "Land Cruiser", "Fortuner", "Innova", "Yaris", "Etios", "Corolla Altis"],
    "mercedes-benz": ["A-Class", "C-Class", "E-Class", "GLA", "GLE", "GLC", "CLS", "AMG GT", "S-Class", "S-Class Coupe"],
    "mahindra": ["Thar", "Scorpio", "XUV500", "Bolero", "KUV100", "TUV300", "XUV300", "Alturas G4", "Marazzo", "Rexton"],
    "maruti": ["Alto", "Baleno", "Ciaz", "Ertiga", "Swift", "Dzire", "Brezzza", "S-Cross", "Celerio", "Ignis", "Wagon R"],
    "kia": ["Seltos", "Sonet", "Carnival", "Sportage", "Sorento", "Stinger", "Niro", "Niro Hybrid", "Niro PHEV", "Soul"],
    "honda": ["City", "Civic", "CRV", "Jazz", "WRV", "Amaze", "Accord", "BR-V", "HR-V", "Pilot"],
    "tata": ["Altroz", "Harrier", "Nano", "Nexon", "Safari", "Tiago", "Tigor", "Hexa", "Zest", "Bolt"]
}

export const carFuelType = ["Petrol", "Diesel", "Electric", "CNG"];
export const carVriants = {
    "chevrolet": {
        "Spark": ["Base", "Premium", "Technology"],
        "Beat": ["Base", "Premium", "Technology"],
        "Cruze": ["Base", "Premium", "Technology"],
        "Tavera": ["Base", "Premium", "Technology"],
        "Camaro": ["Base", "Premium", "Technology"],
        "Colorado": ["Base", "Premium", "Technology"],
        "Equinox": ["Base", "Premium", "Technology"],
        "Silverado": ["Base", "Premium", "Technology"],
        "Trailblazer": ["Base", "Premium", "Technology"],
        "Trax": ["Base", "Premium", "Technology"]
    },
    "ford": {
        "Figo": ["Base", "Premium", "Technology"],
        "Fiesta": ["Base", "Premium", "Technology"],
        "Ecosport": ["Base", "Premium", "Technology"],
        "Endeavour": ["Base", "Premium", "Technology"],
        "Mustang": ["Base", "Premium", "Technology"],
        "Fusion": ["Base", "Premium", "Technology"],
        "Focus": ["Base", "Premium", "Technology"],
        "Explorer": ["Base", "Premium", "Technology"],
        "Edge": ["Base", "Premium", "Technology"],
        "Escape": ["Base", "Premium", "Technology"]
    },
    "skoda": {
        "Rapid": ["Base", "Premium", "Technology"],
        "Octavia": ["Base", "Premium", "Technology"],
        "Superb": ["Base", "Premium", "Technology"],
        "Kodiaq": ["Base", "Premium", "Technology"],
        "Karoq": ["Base", "Premium", "Technology"],
        "Yeti": ["Base", "Premium", "Technology"],
        "Fabia": ["Base", "Premium", "Technology"],
        "Laura": ["Base", "Premium", "Technology"],
        "Superb": ["Base", "Premium", "Technology"]
    },
    "bmw": {
        "X1": ["Base", "Premium", "Technology"],
        "X2": ["Base", "Premium", "Technology"],
        "X3": ["Base", "Premium", "Technology"],
        "X4": ["Base", "Premium", "Technology"],
        "X5": ["Base", "Premium", "Technology"],
        "X6": ["Base", "Premium", "Technology"],
        "X7": ["Base", "Premium", "Technology"],
        "M2": ["Base", "Premium", "Technology"],
        "M3": ["Base", "Premium", "Technology"],
        "M4": ["Base", "Premium", "Technology"],
        "M5": ["Base", "Premium", "Technology"],
        "M6": ["Base", "Premium", "Technology"]
    },
    "volkswagen": {
        "Polo": ["Base", "Premium", "Technology"],
        "Vento": ["Base", "Premium", "Technology"],
        "Jetta": ["Base", "Premium", "Technology"],
        "Passat": ["Base", "Premium", "Technology"],
        "Tiguan": ["Base", "Premium", "Technology"],
        "Touareg": ["Base", "Premium", "Technology"],
        "Amarok": ["Base", "Premium", "Technology"],
        "Golf": ["Base", "Premium", "Technology"],
        "Jetta GLI": ["Base", "Premium", "Technology"],
        "Arteon": ["Base", "Premium", "Technology"]
    },
    "hyundai": {
        "Santro": ["Base", "Premium", "Technology"],
        "i20": ["Base", "Premium", "Technology"],
        "Verna": ["Base", "Premium", "Technology"],
        "Creta": ["Base", "Premium", "Technology"],
        "Tucson": ["Base", "Premium", "Technology"],
        "Elantra": ["Base", "Premium", "Technology"],
        "Santa Fe": ["Base", "Premium", "Technology"],
        "Kona": ["Base", "Premium", "Technology"],
        "Venue": ["Base", "Premium", "Technology"],
        "Grand i10": ["Base", "Premium", "Technology"]
    },
    "nissan": {
        "Micra": ["Base", "Premium", "Technology"],
        "Sunny": ["Base", "Premium", "Technology"],
        "Kicks": ["Base", "Premium", "Technology"],
        "Terrano": ["Base", "Premium", "Technology"],
        "GT-R": ["Base", "Premium", "Technology"],
        "Leaf": ["Base", "Premium", "Technology"],
        "Altima": ["Base", "Premium", "Technology"],
        "Pathfinder": ["Base", "Premium", "Technology"],
        "Rogue": ["Base", "Premium", "Technology"],
        "Xterra": ["Base", "Premium", "Technology"]
    },
    "renault": {
        "Kwid": ["Base", "Premium", "Technology"],
        "Duster": ["Base", "Premium", "Technology"],
        "Triber": ["Base", "Premium", "Technology"],
        "Koleos": ["Base", "Premium", "Technology"],
        "Captur": ["Base", "Premium", "Technology"],
        "Dacia Duster": ["Base", "Premium", "Technology"],
        "Lodgy": ["Base", "Premium", "Technology"],
        "Pulse": ["Base", "Premium", "Technology"],
        "Scala": ["Base", "Premium", "Technology"],
        "Fluence": ["Base", "Premium", "Technology"]
    },
    "fiat": {
        "Punto": ["Base", "Premium", "Technology"],
        "Linea": ["Base", "Premium", "Technology"],
        "500X": ["Base", "Premium", "Technology"],
        "Panda": ["Base", "Premium", "Technology"],
        "Linea Classic": ["Base", "Premium", "Technology"],
        "Avventura": ["Base", "Premium", "Technology"],
        "Urban Cross": ["Base", "Premium", "Technology"],
        "T-Jet": ["Base", "Premium", "Technology"],
        "Cronos": ["Base", "Premium", "Technology"]
    },
    "toyota": {
        "Altis": ["Base", "Premium", "Technology"],
        "Camry": ["Base", "Premium", "Technology"],
        "Corolla": ["Base", "Premium", "Technology"],
        "Highlander": ["Base", "Premium", "Technology"],
        "Land Cruiser": ["Base", "Premium", "Technology"],
        "Fortuner": ["Base", "Premium", "Technology"],
        "Innova": ["Base", "Premium", "Technology"],
        "Yaris": ["Base", "Premium", "Technology"],
        "Etios": ["Base", "Premium", "Technology"],
        "Corolla Altis": ["Base", "Premium", "Technology"]
    },
    "mercedes-benz": {
        "A-Class": ["Base", "Premium", "Technology"],
        "C-Class": ["Base", "Premium", "Technology"],
        "E-Class": ["Base", "Premium", "Technology"],
        "GLA": ["Base", "Premium", "Technology"],
        "GLE": ["Base", "Premium", "Technology"],
        "GLC": ["Base", "Premium", "Technology"],
        "CLS": ["Base", "Premium", "Technology"],
        "AMG GT": ["Base", "Premium", "Technology"],
        "S-Class": ["Base", "Premium", "Technology"],
        "S-Class Coupe": ["Base", "Premium", "Technology"]
    },
    "mahindra": {
        "Thar": ["Base", "Premium", "Technology"],
        "Scorpio": ["Base", "Premium", "Technology"],
        "XUV500": ["Base", "Premium", "Technology"],
        "Bolero": ["Base", "Premium", "Technology"],
        "KUV100": ["Base", "Premium", "Technology"],
        "TUV300": ["Base", "Premium", "Technology"],
        "XUV300": ["Base", "Premium", "Technology"],
        "Alturas G4": ["Base", "Premium", "Technology"],
        "Marazzo": ["Base", "Premium", "Technology"],
        "Rexton": ["Base", "Premium", "Technology"]
    },
    "maruti": {
        "Alto": ["Base", "Premium", "Technology"],
        "Baleno": ["Base", "Premium", "Technology"],
        "Ciaz": ["Base", "Premium", "Technology"],
        "Ertiga": ["Base", "Premium", "Technology"],
        "Swift": ["Base", "Premium", "Technology"],
        "Dzire": ["Base", "Premium", "Technology"],
        "Brezza": ["Base", "Premium", "Technology"],
        "S-Cross": ["Base", "Premium", "Technology"],
        "Celerio": ["Base", "Premium", "Technology"],
        "Ignis": ["Base", "Premium", "Technology"],
        "Wagon R": ["Base", "Premium", "Technology"]
    },
    "kia": {
        "Seltos": ["Base", "Premium", "Technology"],
        "Sonet": ["Base", "Premium", "Technology"],
        "Carnival": ["Base", "Premium", "Technology"],
        "Sportage": ["Base", "Premium", "Technology"],
        "Sorento": ["Base", "Premium", "Technology"],
        "Stinger": ["Base", "Premium", "Technology"],
        "Niro": ["Base", "Premium", "Technology"],
        "Niro Hybrid": ["Base", "Premium", "Technology"],
        "Niro PHEV": ["Base", "Premium", "Technology"],
        "Soul": ["Base", "Premium", "Technology"]
    },
    "honda": {
        "City": ["Base", "Premium", "Technology"],
        "Civic": ["Base", "Premium", "Technology"],
        "CRV": ["Base", "Premium", "Technology"],
        "Jazz": ["Base", "Premium", "Technology"],
        "WRV": ["Base", "Premium", "Technology"],
        "Amaze": ["Base", "Premium", "Technology"],
        "Accord": ["Base", "Premium", "Technology"],
        "BR-V": ["Base", "Premium", "Technology"],
        "HR-V": ["Base", "Premium", "Technology"],
        "Pilot": ["Base", "Premium", "Technology"]
    },
    "tata": {
        "Altroz": ["Base", "Premium", "Technology"],
        "Harrier": ["Base", "Premium", "Technology"],
        "Nano": ["Base", "Premium", "Technology"],
        "Nexon": ["Base", "Premium", "Technology"],
        "Safari": ["Base", "Premium", "Technology"],
        "Tiago": ["Base", "Premium", "Technology"],
        "Tigor": ["Base", "Premium", "Technology"],
        "Hexa": ["Base", "Premium", "Technology"],
        "Zest": ["Base", "Premium", "Technology"],
        "Bolt": ["Base", "Premium", "Technology"]
    }

}
export const carVariants2 = [
    "2.0L 2WD AT",
    "2.4L 2WD",
    "RVI MT",
    "RVI AT",
    "RVSI AT",
    "2.4L 4WD AVN",
    "ACTIVE",
    "MODE",
    "1.2 S MT",
    "1.5 SX I-DTEC",
    "1.5 SV MT DIESEL",
    "SV MT DIESEL",
    "1.5 VX MT PETROL",
    "1.5 SV CVT",
    "1.5 VX CVT",
    "1.5 VX (O) MT",
    "1.5 VX (O) MT DIESEL",
    "1.2 S PLUS I-VTEC",
    "1.2 VX (O) MT I-VTEC",
    "1.5 VX MT (O) I-DTEC",
    "1.2 VX BL MT",
    "V MT PETROL STYLE EDITION",
    "VX MT PETROL STYLE EDITION",
    "LX-BS - IV 7STR",
    "DI EX 9 STR",
    "DI EX 7 STR",
    "DI GX 9 STR",
    "DI GX 7 STR",
]